[package]
name = "cospectra"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
build = "src/build.rs"

[build-dependencies.tauri-build]
version = "2"
features = []

[dependencies]

[dependencies.tauri]
version = "2"
features = ["unstable"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[[bin]]
name = "cospectra"
path = "src/main.rs"
